import { Raleway } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";
import Head from "next/head";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-ral",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body className={`${raleway.variable} font-ral relative`}>
        <main className="max-w-screen">
          <Navbar></Navbar>
          {children}
        </main>
      </body>
    </html>
  );
}
